name: CI

on: [push]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat --version

  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat index.html
      - run: cat main.js
      - run: cat styles.css

  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Finalizado!"
      
