name: CI

on: [push]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 -V

  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 main.py

  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Finalizado!"
      
